### ISSUE TITLE
Application crash at first start

### ISSUE THREAD

**Issue by 0xCA5A** [0xCA5A/jbert#1]
Application does not start the first time:

```
Sep 08 10:31:04 zero jbert[330]: Sep 08, 2019 10:31:04 AM com.google.inject.internal.util.Stopwatch resetAndLog
Sep 08 10:31:04 zero jbert[330]: FINE: Preloading singletons: 20797ms
Sep 08 10:31:04 zero jbert[330]: Oops, cannot start the server.
Sep 08 10:31:04 zero jbert[330]: com.google.inject.CreationException: Unable to create injector, see the following errors:
Sep 08 10:31:04 zero jbert[330]: 1) Error injecting constructor, java.lang.RuntimeException: Unable to open GPIO edge interface for pin 7: Permission denied
Sep 08 10:31:04 zero jbert[330]:   at event.EventRouterImpl.<init>(EventRouterImpl.java:25)
Sep 08 10:31:04 zero jbert[330]:   while locating event.EventRouterImpl
Sep 08 10:31:04 zero jbert[330]:   at modules.BackendModule.configure(BackendModule.java:25) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.ApplicationModule -> modules.BackendModule)
Sep 08 10:31:04 zero jbert[330]:   while locating event.EventRouter
Sep 08 10:31:04 zero jbert[330]: 1 error
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.Guice.createInjector(Guice.java:87)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.Guice.createInjector(Guice.java:78)
Sep 08 10:31:04 zero jbert[330]:         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
Sep 08 10:31:04 zero jbert[330]:         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:156)
Sep 08 10:31:04 zero jbert[330]:         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
Sep 08 10:31:04 zero jbert[330]:         at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
Sep 08 10:31:04 zero jbert[330]:         at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
Sep 08 10:31:04 zero jbert[330]:         at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Sep 08 10:31:04 zero jbert[330]: Caused by: java.lang.RuntimeException: Unable to open GPIO edge interface for pin 7: Permission denied
Sep 08 10:31:04 zero jbert[330]:         at com.pi4j.wiringpi.GpioInterrupt.enablePinStateChangeCallback(Native Method)
Sep 08 10:31:04 zero jbert[330]:         at com.pi4j.io.gpio.WiringPiGpioProviderBase.updateInterruptListener(WiringPiGpioProviderBase.java:325)
Sep 08 10:31:04 zero jbert[330]:         at com.pi4j.io.gpio.WiringPiGpioProviderBase.addListener(WiringPiGpioProviderBase.java:300)
Sep 08 10:31:04 zero jbert[330]:         at com.pi4j.io.gpio.impl.GpioPinImpl.updateInterruptListener(GpioPinImpl.java:471)
Sep 08 10:31:04 zero jbert[330]:         at com.pi4j.io.gpio.impl.GpioPinImpl.addListener(GpioPinImpl.java:492)
Sep 08 10:31:04 zero jbert[330]:         at gpio.GpiListener.registerAction(GpiListener.java:29)
Sep 08 10:31:04 zero jbert[330]:         at gpio.GpioServiceImpl.registerGpiListener(GpioServiceImpl.java:16)
Sep 08 10:31:04 zero jbert[330]:         at event.EventRouterImpl.configureGpiListener(EventRouterImpl.java:43)
Sep 08 10:31:04 zero jbert[330]:         at event.EventRouterImpl.<init>(EventRouterImpl.java:30)
Sep 08 10:31:04 zero jbert[330]:         at event.EventRouterImpl$$FastClassByGuice$$4f3f8bcf.newInstance(<generated>)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
Sep 08 10:31:04 zero jbert[330]:         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
Sep 08 10:31:04 zero jbert[330]:         ... 9 more
Sep 08 10:31:05 zero jbert[330]: Exception in thread "Thread-5" java.lang.RuntimeException: Unable to open GPIO direction interface for pin 23: Permission denied
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.wiringpi.GpioInterrupt.disablePinStateChangeCallback(Native Method)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.WiringPiGpioProviderBase.updateInterruptListener(WiringPiGpioProviderBase.java:329)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.WiringPiGpioProviderBase.removeListener(WiringPiGpioProviderBase.java:308)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.GpioProviderBase.removeAllListeners(GpioProviderBase.java:342)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.GpioProviderBase.shutdown(GpioProviderBase.java:378)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.impl.GpioControllerImpl.shutdown(GpioControllerImpl.java:1051)
Sep 08 10:31:05 zero jbert[330]:         at com.pi4j.io.gpio.impl.GpioControllerImpl$ShutdownHook.run(GpioControllerImpl.java:986)
Sep 08 10:31:05 zero mpd[622]: client: [1] closed
Sep 08 10:31:05 zero systemd[1]: jbert.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 08 10:31:05 zero systemd[1]: jbert.service: Failed with result 'exit-code'.
```

**Comment by 0xCA5A** [comment]
Fixed in version >=  0.3.0
